### ISSUE TITLE
Attitude -> Altitude

### ISSUE THREAD

**Issue by afollestad** [andresR8/AttitudeView#1]
Attitude and Altitude are pretty different things.

<img width="644" alt="screen shot 2017-02-02 at 9 17 59 am" src="https://cloud.githubusercontent.com/assets/1820165/22555199/892987e4-e928-11e6-8d79-e91881dc0241.png">

<img width="640" alt="screen shot 2017-02-02 at 9 18 06 am" src="https://cloud.githubusercontent.com/assets/1820165/22555209/8ce2bd1a-e928-11e6-91c4-2c9e760b45ae.png">

I think you mean altitude for this library 😃

**Comment by andresR8** [comment]
I'm referring to "attitude" as the vehicle's ( robot, aircraft, etc,)  reference with the earth’s horizon. It's commonly used in the drones field as AHRS ( Attitude and Heading Reference System )
